# Generated by Django 3.0.8 on 2020-07-20 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormuser',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='JWT user specific secret'),
        ),
    ]
